### ISSUE TITLE
it's not clear what 'fail' actually means

### ISSUE THREAD

**Issue by AddaxSoft** [trimstray/otseca#2]
does it mean audit fail (you're insecure)
or does it mean the command has failed?

**Comment by trimstray** [comment]
Hi!

Generally, this status means that the command was incorrectly executed.

I will try to expand the information in the case of errors to make them more user-friendly and better guide to what happened.

**Comment by AddaxSoft** [comment]
that will be great, and maybe in addition add an option flag to display errors ?
-v for verbose for exmaple

**Comment by trimstray** [comment]
Hi!

Look at this (from: [parameters](https://github.com/trimstray/otseca#parameters)):

```bash
  Usage:
    otseca <option|long-option>

  Examples:
    otseca --help
    otseca --format html
    otseca --format html --ignore-failed
    otseca --format raw-html --tasks system,network

  Options:
        --help                      show this message
     -f|--format <key>              set output format (key: html/raw-html)
     -t|--tasks <key>               set specific task to do
                                    (key: system, fs, permissions, services, network, other)
        --show-errors               show stderr to output
        --ignore-failed             do not exit with nonzero on commands failed
```
