### ISSUE TITLE
Program Fail and Wifi stop Working

### ISSUE THREAD

**Issue by fcafra** [trimstray/otseca#3]
Hi, 
when launch  otseca in kali distribution,
Linux <host> 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux
..
-- [ Dump system information ] --
...
...
cat /etc/ftpusers       			        [ FAIL ]

After i shoulded change my internet connection to another sid because internet doesn't work.

**Comment by trimstray** [comment]
Can’t reproduce.
